export class InvoiceInfo {
  index: string;
  invName: string;
  invCode: string;
  invNumber: string;
  invDate: string;
  invType: string;
  curr: string;
  invAmt: number;
  file: any;
  remark: string = null;
  expMsg: string = null;
  state: string;    // '0':未满足条件待编辑; '1':已满足条件不可编辑; '2':已满足条件可编辑; '3':上传失败
  uploadMode: string;

  rno: string = null;
  seq: number = 0;
  item: number = 1;
  invcode: string = null;
  invno: string = null;
  amount: number = 0;
  invdate: Date = null;
  taxamount: number = 0;
  oamount: number = 0;
  invstat: string = null;
  abnormalamount: number = 0;
  taxloss: number = 0;
  // curr: string=null;
  undertaker: string = null;
  underwriter: string = null;
  reason: string = null;
  abnormal: string = null;
  paymentName: string = null;
  paymentNo: string = null;
  collectionName: string = null;
  collectionNo: string = null;
  expdesc: string = null;
  expcode: string = null;
  invdesc: string = null;
  paymentStat: boolean = null;
  flag: string = null;
  invtype: string = null;
  salestaxno: string = null;
  salesname: string = null;
  batchno: string = null;
  buyertaxno: string = null;
  buyername: string = null;
  tlprice: number = 0;
  verifycode: string = null;
  salesaddress: string = null;
  salesbank: string = null;
  buyeraddress: string = null;
  buyerbank: string = null;
  pwarea: string = null;
  // remark: string=null;
  drawer: string = null;
  payee: string = null;
  reviewer: string = null;
  machinecode: string = null;
  machineno: string = null;
  verifystat: string = null;
  verifyStateDesc: string = null;
  paymentStatDesc: string = null;
  padatetime: Date = null;
  isfill: boolean = null;
  existautopa: boolean = null;
  uploadmethod: number = 0;
  msg: string = null;
}
