import { TableColumnModel } from 'src/app/shared/models';
import { InvoiceInfo } from './data-item';

export const DetailTableColumn: TableColumnModel[] = [
  {
    title: ('invoice-date'),
    columnKey: 'invdate',
    columnWidth: '90px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.invdate.localeCompare(b.invdate),
  },
  {
    title: ('exp-invoicecategory'),
    columnKey: 'invtype',
    columnWidth: '160px',
    align: 'left',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.invtype.localeCompare(b.invtype),
  },
  {
    title: ('invoice-no'),
    columnKey: 'invno',
    columnWidth: '175px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.invno.localeCompare(b.invno),
  },
  {
    title: ('invoice-code'),
    columnKey: 'invcode',
    columnWidth: '110px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.invcode.localeCompare(b.invcode),
  },
  {
    title: ('total-amount-including-tax'),
    columnKey: 'oamount',
    columnWidth: '105px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.oamount - b.oamount,
  },
  {
    title: ('col.currency'),
    columnKey: 'curr',
    columnWidth: '110px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.curr.localeCompare(b.curr),
  },
  {
    title: ('price-excluding-tax'),
    columnKey: 'amount',
    columnWidth: '110px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.amount - b.amount,
  },
  {
    title: ('tax-amount'),
    columnKey: 'taxamount',
    columnWidth: '100px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.taxamount - b.taxamount,
  },
  {
    title: ('purchaser-name'),
    columnKey: 'buyername',
    columnWidth: '185px',
    align: 'left',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) =>
      a.buyername.localeCompare(b.buyername),
  },
  {
    title: ('seller-name'),
    columnKey: 'sellername',
    columnWidth: '215px',
    align: 'left',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.sellername.localeCompare(b.sellername),
  },
  {
    title: ('seller-tax-number'),
    columnKey: 'salestaxno',
    columnWidth: '175px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.salestaxno.localeCompare(b.salestaxno),
  },
  {
    title: ('invoiceSource'),
    columnKey: 'source',
    columnWidth: '110px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.source.localeCompare(b.source),
  },
  {
    title: ('invoice-request-status'),
    columnKey: 'paytype',
    columnWidth: '130px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.paytype.localeCompare(b.paytype),
  },
  {
    title: ('ers-reimbursement-number'),
    columnKey: 'rno',
    columnWidth: '120px',
    align: 'center',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.rno.localeCompare(b.rno),
  },
  {
    title: ('col.remark'),
    columnKey: 'remarks',
    columnWidth: '100px',
    align: 'left',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.remarks.localeCompare(b.remarks),
  },
  {
    title: ('causes-of-exceptions'),
    columnKey: 'abnormalreason',
    columnWidth: '160px',
    align: 'left',
    sortFn: (a: InvoiceInfo, b: InvoiceInfo) => a.abnormalreason.localeCompare(b.abnormalreason),
  },
];
